import { useState } from 'react';
import { Download, Copy, FileText, AlertCircle, CheckCircle } from 'lucide-react';
import type { Sensor } from '../types/instana';
import { generateYaml, generateEnv, generateBundle } from '../services/api';

interface OutputPreviewProps {
  selectedSensors: Sensor[];
  tags: Record<string, string>;
  additionalTags: Array<{ key: string; value: string }>;
}

export default function OutputPreview({
  selectedSensors,
  tags,
  additionalTags,
}: OutputPreviewProps) {
  const [activeTab, setActiveTab] = useState<'yaml' | 'env' | 'notes'>('yaml');
  const [copied, setCopied] = useState(false);

  const validationIssues = selectedSensors.flatMap((sensor: Sensor) => 
    (sensor.validation_results || []).filter((v) => v.level === 'ERROR' || v.level === 'WARNING')
  );

  const handleCopy = async () => {
    const content = activeTab === 'yaml' ? generateYamlPreview() : generateEnvPreview();
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    try {
      if (activeTab === 'yaml') {
        const blob = await generateYaml(selectedSensors);
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'configuration.yaml';
        a.click();
      } else if (activeTab === 'env') {
        const blob = await generateEnv(selectedSensors);
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = '.env.example';
        a.click();
      }
    } catch (error) {
      console.error('Download failed:', error);
    }
  };

  const handleDownloadBundle = async () => {
    try {
      const blob = await generateBundle(selectedSensors);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'instana-config-bundle.zip';
      a.click();
    } catch (error) {
      console.error('Bundle download failed:', error);
    }
  };

  const generateYamlPreview = () => {
    return `# Generated by Instana ConfigPilot
# Source: Default Instana template v2026.05
# Template: v2026.05

com.instana.plugin.host:
  enabled: true
  tags:
    - client=${tags.client}
    - environment=${tags.environment}
${tags.zone ? `    - zone=${tags.zone}` : ''}
${tags.owner ? `    - owner=${tags.owner}` : ''}
${additionalTags.filter((t) => t.key && t.value).map((t) => `    - ${t.key}=${t.value}`).join('\n')}

${selectedSensors.map((sensor: Sensor) => `${sensor.name}:
  enabled: ${sensor.enabled}
  ${sensor.configuration ? Object.entries(sensor.configuration).map(([k, v]) => `${k}: ${v}`).join('\n  ') : ''}`).join('\n\n')}`;
  };

  const generateEnvPreview = () => {
    return `# Environment variables for Instana configuration
# Generated by Instana ConfigPilot

${selectedSensors.filter((s: Sensor) => s.credentials && s.credentials.length > 0).map((sensor: Sensor) => 
  `# ${sensor.name}\n${(sensor.credentials || []).map((c) => `${c.env_var}=${c.value || ''}`).join('\n')}`
).join('\n\n')}`;
  };

  return (
    <div className="space-y-4">
      {/* RESULT Section */}
      <div className="bg-dark-card rounded-lg border border-dark-border">
        <div className="border-b border-dark-border p-4">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h2 className="text-sm font-semibold text-primary uppercase tracking-wider">
                RESULT
              </h2>
              <h3 className="text-lg font-bold text-white mt-1">Output Preview</h3>
            </div>
            {selectedSensors.length > 0 && (
              <span className="px-3 py-1 bg-red-500/20 text-red-400 text-sm font-medium rounded-full">
                Needs Action
              </span>
            )}
          </div>

          {/* Tabs */}
          <div className="flex gap-2">
            <button
              onClick={() => setActiveTab('yaml')}
              className={`px-4 py-2 rounded-lg font-medium text-sm transition-colors ${
                activeTab === 'yaml'
                  ? 'bg-primary text-white'
                  : 'bg-dark-hover text-gray-300 hover:bg-dark-border'
              }`}
            >
              configuration.yaml
            </button>
            <button
              onClick={() => setActiveTab('env')}
              className={`px-4 py-2 rounded-lg font-medium text-sm transition-colors ${
                activeTab === 'env'
                  ? 'bg-primary text-white'
                  : 'bg-dark-hover text-gray-300 hover:bg-dark-border'
              }`}
            >
              .env.example
            </button>
            <button
              onClick={() => setActiveTab('notes')}
              className={`px-4 py-2 rounded-lg font-medium text-sm transition-colors ${
                activeTab === 'notes'
                  ? 'bg-primary text-white'
                  : 'bg-dark-hover text-gray-300 hover:bg-dark-border'
              }`}
            >
              Bob notes
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="p-4">
          {activeTab === 'yaml' && (
            <div>
              <div className="flex items-center justify-between mb-3">
                <h4 className="font-semibold text-white">configuration.yaml</h4>
                <div className="flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="px-3 py-1.5 bg-dark-hover hover:bg-dark-border text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                  >
                    {copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="px-3 py-1.5 bg-primary hover:bg-primary/90 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                  >
                    <Download className="w-4 h-4" />
                    Download
                  </button>
                </div>
              </div>
              <p className="text-sm text-gray-400 mb-3">
                Generated from selected sensors and tags
              </p>

              {selectedSensors.length === 0 ? (
                <div className="bg-dark-hover rounded-lg p-8 text-center border border-dark-border">
                  <FileText className="w-12 h-12 mx-auto mb-3 text-gray-500" />
                  <p className="text-gray-400">No sensors selected</p>
                  <p className="text-sm text-gray-500 mt-1">
                    Select sensors from the catalog to generate YAML
                  </p>
                </div>
              ) : (
                <div className="bg-[#0d1117] rounded-lg border border-dark-border overflow-hidden">
                  <pre className="p-4 text-sm text-gray-300 overflow-x-auto">
                    <code>{generateYamlPreview()}</code>
                  </pre>
                </div>
              )}
            </div>
          )}

          {activeTab === 'env' && (
            <div>
              <div className="flex items-center justify-between mb-3">
                <h4 className="font-semibold text-white">.env.example</h4>
                <div className="flex gap-2">
                  <button
                    onClick={handleCopy}
                    className="px-3 py-1.5 bg-dark-hover hover:bg-dark-border text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                  >
                    {copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                  <button
                    onClick={handleDownload}
                    className="px-3 py-1.5 bg-primary hover:bg-primary/90 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                  >
                    <Download className="w-4 h-4" />
                    Download
                  </button>
                </div>
              </div>

              {selectedSensors.length === 0 ? (
                <div className="bg-dark-hover rounded-lg p-8 text-center border border-dark-border">
                  <FileText className="w-12 h-12 mx-auto mb-3 text-gray-500" />
                  <p className="text-gray-400">No environment variables</p>
                </div>
              ) : (
                <div className="bg-[#0d1117] rounded-lg border border-dark-border overflow-hidden">
                  <pre className="p-4 text-sm text-gray-300 overflow-x-auto">
                    <code>{generateEnvPreview()}</code>
                  </pre>
                </div>
              )}
            </div>
          )}

          {activeTab === 'notes' && (
            <div>
              <h4 className="font-semibold text-white mb-3">Bob notes</h4>
              <div className="space-y-3">
                <div className="bg-dark-hover rounded-lg p-3 border border-dark-border">
                  <p className="text-sm text-gray-300">
                    Configuration generated successfully. Review the validation findings below before deployment.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Validation & Findings */}
      <div className="bg-dark-card rounded-lg border border-dark-border p-4">
        <div className="flex items-center justify-between mb-3">
          <h4 className="font-semibold text-white">Validation & Findings</h4>
          <span className="text-sm text-gray-400">{validationIssues.length} finding(s)</span>
        </div>
        <p className="text-sm text-gray-400 mb-3">
          Syntax, required fields and security warnings
        </p>

        {validationIssues.length === 0 ? (
          <div className="flex items-center gap-2 text-green-400 text-sm">
            <CheckCircle className="w-4 h-4" />
            <span>No validation issues found</span>
          </div>
        ) : (
          <div className="space-y-2">
            {validationIssues.map((issue, index) => (
              <div
                key={index}
                className={`flex items-start gap-2 p-3 rounded-lg ${
                  issue.level === 'ERROR'
                    ? 'bg-red-500/10 border border-red-500/20'
                    : 'bg-yellow-500/10 border border-yellow-500/20'
                }`}
              >
                <AlertCircle
                  className={`w-4 h-4 mt-0.5 flex-shrink-0 ${
                    issue.level === 'ERROR' ? 'text-red-400' : 'text-yellow-400'
                  }`}
                />
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span
                      className={`text-xs font-medium ${
                        issue.level === 'ERROR' ? 'text-red-400' : 'text-yellow-400'
                      }`}
                    >
                      {issue.level === 'ERROR' ? '● Missing zone tag' : '● Missing owner tag'}
                    </span>
                  </div>
                  <p className="text-sm text-gray-300">{issue.message}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Download Bundle Button */}
      {selectedSensors.length > 0 && (
        <button
          onClick={handleDownloadBundle}
          className="w-full px-4 py-3 bg-primary hover:bg-primary/90 text-white rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
        >
          <Download className="w-5 h-5" />
          Download Complete Bundle (ZIP)
        </button>
      )}
    </div>
  );
}

// Made with Bob