"""Environment file generator"""
from typing import List, Dict, Set
from app.models.sensor import Sensor


class EnvGenerator:
    """Generate .env files from sensor configurations"""

    SENSITIVE_FIELDS = [
        'password', 'token', 'secret', 'api_key', 'apikey',
        'access_token', 'secret_key', 'client_secret',
        'access_key', 'secret_access_key', 'private_key',
        'auth_token', 'bearer_token'
    ]

    def generate(self, sensors: List[Sensor]) -> str:
        """
        Generate .env file content from sensors

        Args:
            sensors: List of sensors to generate env vars from

        Returns:
            String content for .env file
        """
        env_lines = [
            "# Generated by Instana Config Pilot",
            "# Environment variables for Instana configuration",
            "#",
            "# IMPORTANT: Fill in the values before using this file",
            "# Rename this file to .env after filling in the values",
            "#",
            "# Usage: These variables can be referenced in configuration.yaml",
            "",
        ]

        # Group sensors by category
        sensors_by_category = {}
        for sensor in sensors:
            if sensor.enabled and sensor.env_variables:
                category = sensor.category.value
                if category not in sensors_by_category:
                    sensors_by_category[category] = []
                sensors_by_category[category].append(sensor)

        # Generate env vars by category
        for category in sorted(sensors_by_category.keys()):
            category_sensors = sensors_by_category[category]
            
            env_lines.append(f"# ===== {category.upper().replace('_', ' ')} =====")
            env_lines.append("")

            for sensor in sorted(category_sensors, key=lambda s: s.name):
                env_lines.append(f"# Sensor: {sensor.display_name} ({sensor.name})")
                
                if sensor.description:
                    env_lines.append(f"# {sensor.description}")

                for env_var in sorted(sensor.env_variables):
                    # Add helpful comment about the variable
                    field_name = env_var.split('_')[-1].lower()
                    env_lines.append(f"# {field_name.title()} for {sensor.display_name}")
                    env_lines.append(f"{env_var}=")

                env_lines.append("")

        # Add usage instructions at the end
        env_lines.extend([
            "",
            "# ===== USAGE INSTRUCTIONS =====",
            "#",
            "# 1. Fill in all the values above",
            "# 2. Rename this file from .env.example to .env",
            "# 3. Make sure .env is in your .gitignore",
            "# 4. Reference these variables in your configuration.yaml",
            "#",
            "# Example in configuration.yaml:",
            "# com.instana.plugin.mysql:",
            "#   password: ${MYSQL_PASSWORD}",
            "#",
            "# Or use Vault for better security:",
            "# com.instana.plugin.mysql:",
            "#   password:",
            "#     configuration_from:",
            "#       type: vault",
            "#       secret_key:",
            "#         path: secret/mysql",
            "#         key: password",
            ""
        ])

        return '\n'.join(env_lines)

    def detect_env_variables(self, sensor: Sensor) -> List[str]:
        """
        Detect which fields should be environment variables

        Args:
            sensor: Sensor to analyze

        Returns:
            List of environment variable names
        """
        env_vars = []

        if not isinstance(sensor.config, dict):
            return env_vars

        def check_dict(d: Dict, prefix: str = ""):
            for key, value in d.items():
                current_key = f"{prefix}_{key}" if prefix else key

                # Skip if using Vault
                if isinstance(value, dict) and 'configuration_from' in value:
                    continue

                # Check if field is sensitive
                if any(field in key.lower() for field in self.SENSITIVE_FIELDS):
                    var_name = f"{sensor.name.replace('.', '_').upper()}_{current_key.upper()}"
                    env_vars.append(var_name)

                # Recursively check nested dicts
                elif isinstance(value, dict):
                    check_dict(value, current_key)

        check_dict(sensor.config)
        return env_vars

    def get_env_var_summary(self, sensors: List[Sensor]) -> Dict[str, int]:
        """
        Get summary of environment variables by category

        Args:
            sensors: List of sensors

        Returns:
            Dictionary with category counts
        """
        summary = {}
        
        for sensor in sensors:
            if sensor.enabled and sensor.env_variables:
                category = sensor.category.value
                count = len(sensor.env_variables)
                summary[category] = summary.get(category, 0) + count

        return summary

# Made with Bob
