"""YAML configuration file generator"""
import yaml
from typing import List, Dict, Any
from app.models.sensor import Sensor


class YAMLGenerator:
    """Generate Instana configuration.yaml files"""

    def generate(self, sensors: List[Sensor], include_comments: bool = True) -> str:
        """
        Generate configuration.yaml content from sensors

        Args:
            sensors: List of sensors to include
            include_comments: Whether to include helpful comments

        Returns:
            String content for configuration.yaml
        """
        lines = []

        if include_comments:
            lines.extend([
                "# Instana Agent Configuration",
                "# Generated by Instana Config Pilot",
                "#",
                "# This file contains the configuration for Instana host agent sensors.",
                "# Only enabled sensors are included in this configuration.",
                "#",
                "# For more information, visit:",
                "# https://www.ibm.com/docs/en/instana-observability",
                "",
            ])

        # Group sensors by category
        sensors_by_category = {}
        for sensor in sensors:
            category = sensor.category.value
            if category not in sensors_by_category:
                sensors_by_category[category] = []
            sensors_by_category[category].append(sensor)

        # Generate configuration by category
        for category in sorted(sensors_by_category.keys()):
            category_sensors = sensors_by_category[category]
            
            if include_comments:
                lines.append(f"# ===== {category.upper().replace('_', ' ')} =====")
                lines.append("")

            for sensor in sorted(category_sensors, key=lambda s: s.name):
                # Add sensor comment
                if include_comments:
                    lines.append(f"# {sensor.display_name}")
                    if sensor.description:
                        lines.append(f"# {sensor.description}")

                # Add sensor configuration
                sensor_yaml = self._format_sensor_config(sensor)
                lines.append(sensor_yaml)
                lines.append("")

        return '\n'.join(lines)

    def _format_sensor_config(self, sensor: Sensor) -> str:
        """Format a single sensor configuration"""
        if not sensor.config:
            return f"{sensor.name}:"

        # Create a clean config dict
        config_dict = {sensor.name: sensor.config}

        # Convert to YAML with proper formatting
        yaml_str = yaml.dump(
            config_dict,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            width=120
        )

        # Remove the trailing newline
        return yaml_str.rstrip('\n')

    def generate_minimal(self, sensors: List[Sensor]) -> str:
        """
        Generate minimal configuration with only enabled sensors

        Args:
            sensors: List of sensors

        Returns:
            Minimal YAML configuration
        """
        enabled_sensors = [s for s in sensors if s.enabled]
        return self.generate(enabled_sensors, include_comments=False)

    def generate_with_env_vars(self, sensors: List[Sensor]) -> str:
        """
        Generate configuration with environment variable placeholders

        Args:
            sensors: List of sensors

        Returns:
            YAML configuration with ${VAR} placeholders
        """
        lines = [
            "# Instana Agent Configuration",
            "# Generated by Instana Config Pilot with Environment Variables",
            "#",
            "# Environment variables are referenced using ${VARIABLE_NAME} syntax",
            "# Make sure to set these variables before starting the agent",
            "",
        ]

        for sensor in sorted(sensors, key=lambda s: (s.category.value, s.name)):
            if not sensor.enabled:
                continue

            lines.append(f"# {sensor.display_name}")
            
            # Replace sensitive values with env var references
            config = self._replace_with_env_vars(sensor)
            
            config_dict = {sensor.name: config}
            yaml_str = yaml.dump(
                config_dict,
                default_flow_style=False,
                sort_keys=False,
                allow_unicode=True
            )
            
            lines.append(yaml_str.rstrip('\n'))
            lines.append("")

        return '\n'.join(lines)

    def _replace_with_env_vars(self, sensor: Sensor) -> Dict[str, Any]:
        """Replace sensitive values with environment variable references"""
        config = sensor.config.copy()

        sensitive_fields = [
            'password', 'token', 'api_key', 'secret_key', 'access_token',
            'apikey', 'client_secret', 'secret', 'private_key'
        ]

        def replace_in_dict(d: Dict[str, Any], prefix: str = "") -> Dict[str, Any]:
            result = {}
            for key, value in d.items():
                current_key = f"{prefix}_{key}" if prefix else key

                # Skip if using Vault
                if isinstance(value, dict) and 'configuration_from' in value:
                    result[key] = value
                    continue

                # Replace sensitive fields
                if any(field in key.lower() for field in sensitive_fields):
                    var_name = f"{sensor.name.replace('.', '_').upper()}_{current_key.upper()}"
                    result[key] = f"${{{var_name}}}"
                elif isinstance(value, dict):
                    result[key] = replace_in_dict(value, current_key)
                else:
                    result[key] = value

            return result

        return replace_in_dict(config)

# Made with Bob
