export function generateEnv(activeSensors, catalog) {
  const vars = new Set();
  activeSensors.forEach(sensor => {
    (catalog[sensor.type]?.env || []).forEach(name => vars.add(name));
  });

  const lines = [
    '# Generated by Instana ConfigPilot',
    '# Fill sensitive values outside configuration.yaml',
    ''
  ];

  vars.forEach(name => lines.push(`${name}=`));
  if (!vars.size) lines.push('# No environment variables required by selected sensors.');
  return lines.join('\n');
}
