import { ActiveSensor } from './yamlGenerator';
import { SensorCatalog } from './sensorCatalog';

export function generateEnv(activeSensors: ActiveSensor[], catalog: SensorCatalog): string {
  const vars = new Set<string>();
  activeSensors.forEach(sensor => {
    (catalog[sensor.type]?.env || []).forEach(name => vars.add(name));
  });

  const lines = [
    '# Generated by Instana ConfigPilot',
    '# Fill sensitive values outside configuration.yaml',
    ''
  ];

  vars.forEach(name => lines.push(`${name}=`));
  if (!vars.size) lines.push('# No environment variables required by selected sensors.');
  return lines.join('\n');
}

// Made with Bob
