import { SensorCatalog } from './sensorCatalog';
import { Tag } from './sensorDetector';

const ENV_PREFIX = '${';

export interface ActiveSensor {
  id: string;
  type: string;
  config: Record<string, any>;
  required?: boolean;
}

export interface GenerateYamlParams {
  sourceName: string;
  templateVersion: string;
  tags: Tag[];
  activeSensors: ActiveSensor[];
  catalog: SensorCatalog;
}

export function safeYamlValue(value: any): string {
  if (value === undefined || value === null) return '';
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  const text = String(value).trim();
  if (!text) return '';
  if (text.includes(':') && !text.startsWith(ENV_PREFIX)) return JSON.stringify(text);
  return text;
}

function quoteYamlString(value: string): string {
  return `'${String(value).replace(/'/g, "''")}'`;
}

export function generateYaml({ sourceName, templateVersion, tags, activeSensors, catalog }: GenerateYamlParams): string {
  const hostTags = tags
    .filter(tag => String(tag.key || '').trim() && String(tag.value || '').trim())
    .map(tag => `${safeYamlValue(tag.key)}=${safeYamlValue(tag.value)}`);

  const lines = [
    '# Generated by Instana ConfigPilot',
    `# Source: ${sourceName}`,
    `# Template: ${templateVersion}`,
    '',
    'com.instana.plugin.host:',
  ];

  if (hostTags.length) {
    lines.push('  tags:');
    hostTags.forEach(tag => lines.push(`    - ${quoteYamlString(tag)}`));
  } else {
    lines.push('  # Add tag values in Template & Tags to populate this section.');
  }

  lines.push('');

  activeSensors.forEach(sensor => {
    if (sensor.type === 'host') return;
    const meta = catalog[sensor.type];
    if (!meta) return;
    lines.push(`${meta.yamlKey}:`);
    lines.push('  enabled: true');

    if (sensor.type === 'ibmmq') {
      renderIbmMq(sensor.config || {}, lines);
      lines.push('');
      return;
    }

    Object.keys(sensor.config || {}).forEach(key => {
      if (key === 'enabled') return;
      lines.push(`  ${key}: ${safeYamlValue(sensor.config[key])}`);
    });
    lines.push('');
  });

  return lines.join('\n');
}

function renderIbmMq(config: Record<string, any>, lines: string[]): void {
  const topLevel = ['poll_rate', 'enableStatisticsQueueMetrics', 'support_ha', 'aggregateChannelInstances'];
  topLevel.forEach(key => {
    if (config[key] !== undefined && config[key] !== '') lines.push(`  ${key}: ${safeYamlValue(config[key])}`);
  });

  const qm = config.queueManagerName || 'QUEUE_MANAGER_NAME';
  lines.push('  queueManagers:');
  lines.push(`    ${safeYamlValue(qm)}:`);
  ['host', 'port', 'channel', 'username', 'password', 'keystore', 'keystorePassword', 'cipherSuite'].forEach(key => {
    if (config[key] !== undefined && config[key] !== '') lines.push(`      ${key}: ${safeYamlValue(config[key])}`);
  });
}

// Made with Bob
